### ISSUE TITLE
not work 

### ISSUE THREAD

**Issue by meeidoo** [Alplox/xtreamcode1.0.60#1]
not work this virgin he is did 
show massage
 [sudo] password for xtreamcodes:

**Comment by Alplox** [comment]
Of course it doesn't work, Xtream Codes was takedown, read this articles for more information:
https://www.firesticktricks.com/authorities-target-iptv-providers-xtream-codes-taken-down.html
https://torrentfreak.com/the-xtream-codes-iptv-takedown-is-complex-and-confused-190919/

I'm going to ignore your attitude and giving you this alternative, is only on spanish, but i guess you know how to translate stuff:
https://www.apuntesplox.xyz/2019/11/como-instalar-xtreamui-iptv-ubuntu-1804.html
